# =====================================================
# OrangeHRM Automation Framework - Environment Config
# =====================================================
base.url=https://opensource-demo.orangehrmlive.com/web/index.php/auth/login
browser=chrome
implicit.wait.seconds=10
explicit.wait.seconds=15

# Valid Admin credentials (OrangeHRM public demo)
valid.username=Admin
valid.password=admin123

# Invalid credentials (for negative login test)
invalid.username=Admin
invalid.password=wrongPass123
